---
- name: Ensure GlusterFS is installed 
  apt:
    name:
    - glusterfs-client
    - glusterfs-server
    state: present

- name: Ensure Gluster services are started and enabled
  service: 
    name: glusterd
    state: started
    enabled: yes