---
# pkgs were failing occasionally on install; retries added
- name : Install / Start GlusterFS Services
  apt:
    state: present
    name: 
      - glusterfs-client
      - glusterfs-server
  register: apt_res
  retries: 5
  until: apt_res is success
  notify:
    - enable glusterfs-server
    - start glusterfs-server

# - name: Ensure Gluster services are started and enabled
#   service: 
#     name: glusterd
#     state: started
#     enabled: yes  