- name: Deploy GlusterFS cluster
  hosts: all
  become: True
  gather_facts: true
  vars_files: 
    - vars.yml
  
  roles:
    - common
    - firewall
    - glusterfs
  
  tasks:

    # - name: Wait for SSH to be ready
    #   local_action: wait_for port=22 host="{{ ip }}"  search_regex=OpenSSH delay=10

    #turn facts back on after we have a connection
    - name: Gathering facts
      setup:

    # - name: Display all variables/facts known for a host
    #   debug:
    #     var: hostvars[inventory_hostname]

    - name: Ensure Gluster brick and mount directories exist.
      file: 
        path: "{{ item }}"
        state: directory 
        mode: 0775
      loop:
          - "{{ gluster_brick_dir }}"
          - "{{ gluster_mount_dir }}"

    - debug: var=inventory_hostname
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address

    - name: Configure Gluster volume.
      gluster_volume:
        state: present
        name: "{{ gluster_brick_name }}"
        brick: "{{ gluster_brick_dir }}"
        replicas: "{{ nodes }}"
        #dyn inv - grab inv from ec2.py and pass into ansible in json format
        cluster: "{{ private_ips }}"
        host: "{{ ansible_default_ipv4.address }}"
        force: yes
      run_once: true

    - name: Ensure Gluster volume is mounted.
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ ansible_default_ipv4.address }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted